[package]
name = "FreePlugin"
version = "0.1.0"

[addresses]
StarcoinFramework = "0x1"
FreePlugin = "0xf2aa2eae4ceaae88b308fc904975e4ae"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}
