[package]
name = "FreePlugin"
version = "0.1.0"

[addresses]
FreePlugin = "0xA550C19"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}